export const LINE_LIST_REQUEST = 'LINE_LIST_REQUEST' 
export const LINE_LIST_SUCCESS = 'LINE_LIST_SUCCESS' 
export const LINE_LIST_FAIL = 'LINE_LIST_FAIL' 

export const LINE_DETAILS_REQUEST = 'LINE_DETAILS_REQUEST' 
export const LINE_DETAILS_SUCCESS = 'LINE_DETAILS_SUCCESS' 
export const LINE_DETAILS_FAIL = 'LINE_DETAILS_FAIL' 